sudo: required
language: elixir
elixir:
  - 1.4
env:
  - MIX_ENV=test
services:
  - docker
env:
  - MIX_ENV=test
before_install:
  - docker build -t jeremymiller/portals .
script:
  - docker run -it --rm jeremymiller/portals mix credo
  - docker run -it --rm jeremymiller/portals mix test
after_success:
  - mix coveralls.travis  # not working inside docker container
