sudo: required
services:
  - docker
env:
  - MIX_ENV=test
  - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN
before_install:
  - docker build -t jeremymiller/portals .
script:
  - docker run -it --rm jeremymiller/portals mix credo
  - docker run -it --rm jeremymiller/portals mix test
after_success:
  - docker run -it --rm jeremymiller/portals mix coveralls.post
